---
- name: Verify
  hosts: "{{ molecule_robotframework_hosts | d('all') }}"
  tasks:
    #------------------------------------------------------------------
    # Install Robot Framework.
    #
    - import_role:
        name: robotframework
      vars:
        robotframework_install: "{{ molecule_yml.verifier.install | d('auto') }}"
        robotframework_package_name: "{{ molecule_yml.verifier.package_name | d('robotframework') }}"
        robotframework_package_version_spec: "{{ molecule_yml.verifier.package_version_spec | d('') }}"
        robotframework_external_libraries: "{{ molecule_yml.verifier.libraries | d([]) }}"

    - name: Copy Robot Framework argument file.
      copy:
        src: "{{ molecule_ephemeral_directory }}/robotrc"
        dest: "robotrc"
        mode: "644"

    - include_tasks: tasks/compat/resources.yml
      when:
        - molecule_yml.verifier.resources is defined

    - include_tasks: tasks/compat/test_sources.yml
      when: >
        molecule_yml.verifier.test_data is defined or
        molecule_yml.verifier.test_repos is defined
