---
- name: Install python pip.
  include_tasks: "{{ item }}"
  with_first_found:
    - "{{ role_path }}/tasks/pip/{{ ansible_distribution | replace(' ', '_') }}-{{ ansible_distribution_version }}.yml"
    - "{{ role_path }}/tasks/pip/{{ ansible_distribution | replace(' ', '_') }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ role_path }}/tasks/pip/{{ ansible_distribution | replace(' ', '_') }}.yml"
    - "{{ role_path }}/tasks/pip/{{ ansible_os_family }}.yml"
    - "{{ role_path }}/tasks/pip/unknown.yml"

- name: Install Robot Framework.
  become: yes
  pip:
    state: present
    name:
      # Install pyyaml so `robot` will support yaml format variable files.
      - "pyyaml{{ pyyaml_version | d('') }}"
      - "{{ robotframework_package_name }}{{ robotframework_package_version_spec }}"
    executable: "{{ pip_executable | d('pip3') }}"

- name: Install Robot Framework Test Libraries.
  become: yes
  pip:
    state: present
    name: "{{ robotframework_external_libraries }}"
    executable: "{{ pip_executable | d('pip3') }}"
  when: robotframework_external_libraries | count > 0
